src/Entity/LineShoppingBag.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LineShoppingBagRepository")
 */
class LineShoppingBag
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ShoppingCard", inversedBy="lineShoppingBags")
     * @ORM\JoinColumn(nullable=false)
     */
    private $shoppingBag;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Product", inversedBy="lineShoppingBags")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Product;

    public function getId()
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getShoppingBag(): ?ShoppingCard
    {
        return $this->shoppingBag;
    }

    public function setShoppingBag(?ShoppingCard $shoppingBag): self
    {
        $this->shoppingBag = $shoppingBag;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->Product;
    }

    public function setProduct(?Product $Product): self
    {
        $this->Product = $Product;

        return $this;
    }
}

src/Controller/ShoppingCartController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Session\Session;
use App\Entity\ShoppingCard;
use Doctrine\Common\Persistence\ObjectManager;

class ShoppingCartController extends Controller
{
   /**
     * @Route("/user/shopping-cart", name="shopping_cart")
     */
    public function index(Session $session = null, ObjectManager $manager)
    {
            if(!$session) {
            $session = new Session();
            }
            $session->start();

            $cart = $session->get("cart");
            if(!$cart){
                $cart = new ShoppingCard();
            }

            $totalPrice = 0;
            foreach($cart->getLineShoppingBags() as $line) {
                $totalPrice = $totalPrice + $line->getPrice();
            }
            
        

            $cart = $this->getDoctrine()->getManager()->merge($cart);
            $productLine = $cart->getLineShoppingBags();

            $session->set("cart", $cart);
            

            $manager->persist($cart);
            $manager->flush();
            
        return $this->render('shopping_cart/index.html.twig', [
            "productLine" => $productLine,
            "totalPrice" => $totalPrice
        ]);
    }

}

templates/shopping_cart/index.html.twig
{% extends 'base.html.twig' %}

{% block main %}

<h2 class="shopping-cart">Shopping-cart</h2>



<div class="container-fluid">
      
        <table class="table " >
          <thead>
            <tr>
              <th>Product</th>
              <th>Quantity</th>
              <th>Price</th>
              <th>Options</th>

            </tr>
          </thead>
           {% for row in productLine %}
          <tbody>
        
            <tr class="table ">
                    <td>{{row.product.name}}</td>
                    <td>{{row.quantity}}</td>
                    <td>{{row.price}}.00$</td>
                    <td><a class="btn" style="color:black;" href="{{ path("remove_productLine", {"id": row.id}) }}"><i class="fas fa-trash-alt"></i></a></td>

            </tr>
         
          </tbody> 
            {% endfor %}
        </table>
    </div>
      
<p class="priceTotal">Total Shopping: {{totalPrice}}.00$</p>



{% endblock %}